# Decision Tree

In [40]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from xgboost import XGBClassifier

In [41]:
df = pd.read_csv('Dataset_test30092021_for_python.csv')

In [42]:
df.head(5)

mob_inet  fix_inet  fix_ctv  fix_ictv  voice_mob  voice_fix  sms  csd  iot  \
0         0         0        0         0          0          0    0    0    0   
1         0         0        0         0          1          0    0    0    0   
2         0         0        0         0          1          0    0    0    0   
3         0         0        0         0          1          0    0    1    0   
4         0         0        0         0          0          0    0    0    0   

   mms  ...  skoring  other_service  voice_mail  geo  ep_for_number  \
0    0  ...        0              0           0    0              0   
1    0  ...        0              0           0    0              0   
2    0  ...        0              0           0    0              0   
3    0  ...        0              0           0    0              0   
4    0  ...        0              0           0    0              0   

   ep_for_line  one-time_fee_for_number  equipment rent  add_package  group_id  
0            0                        0               0            0         1  
1            0                        0               0            0         1  
2            0                        0               0            0         1  
3            0                        0               0            0         1  
4            0                        0               0            0         1  

[5 rows x 41 columns]

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mob_inet                 540 non-null    int64
 1   fix_inet                 540 non-null    int64
 2   fix_ctv                  540 non-null    int64
 3   fix_ictv                 540 non-null    int64
 4   voice_mob                540 non-null    int64
 5   voice_fix                540 non-null    int64
 6   sms                      540 non-null    int64
 7   csd                      540 non-null    int64
 8   iot                      540 non-null    int64
 9   mms                      540 non-null    int64
 10  roaming                  540 non-null    int64
 11  mg                       540 non-null    int64
 12  mn                       540 non-null    int64
 13  mts                      540 non-null    int64
 14  conc                     540 non-null    int64
 15  fix_op

In [44]:
df.describe()

mob_inet    fix_inet     fix_ctv    fix_ictv   voice_mob   voice_fix  \
count  540.000000  540.000000  540.000000  540.000000  540.000000  540.000000   
mean     0.101852    0.096296    0.094444    0.075926    0.366667    0.242593   
std      0.302734    0.295271    0.292717    0.265125    0.482341    0.429048   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000    0.000000    0.000000    1.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

              sms         csd         iot         mms  ...  skoring  \
count  540.000000  540.000000  540.000000  540.000000  ...    540.0   
mean     0.109259    0.103704    0.064815    0.025926  ...      0.0   
std      0.312253    0.305158    0.246427    0.159062  ...      0.0   
min      0.000000    0.000000    0.000000    0.000000  ...      0.0   
25%      0.000000    0.000000    0.000000    0.000000  ...      0.0   
50%      0.000000    0.000000    0.000000    0.000000  ...      0.0   
75%      0.000000    0.000000    0.000000    0.000000  ...      0.0   
max      1.000000    1.000000    1.000000    1.000000  ...      0.0   

       other_service  voice_mail         geo  ep_for_number  ep_for_line  \
count     540.000000  540.000000  540.000000     540.000000   540.000000   
mean        0.025926    0.020370    0.018519       0.018519     0.024074   
std         0.159062    0.141395    0.134942       0.134942     0.153421   
min         0.000000    0.000000    0.000000       0.000000     0.000000   
25%         0.000000    0.000000    0.000000       0.000000     0.000000   
50%         0.000000    0.000000    0.000000       0.000000     0.000000   
75%         0.000000    0.000000    0.000000       0.000000     0.000000   
max         1.000000    1.000000    1.000000       1.000000     1.000000   

       one-time_fee_for_number  equipment rent  add_package     group_id  
count               540.000000      540.000000        540.0   540.000000  
mean                  0.018519        0.018519          0.0  1290.487037  
std                   0.134942        0.134942          0.0  1343.436513  
min                   0.000000        0.000000          0.0     1.000000  
25%                   0.000000        0.000000          0.0    29.000000  
50%                   0.000000        0.000000          0.0  1011.500000  
75%                   0.000000        0.000000          0.0  3009.000000  
max                   1.000000        1.000000          0.0  3323.000000  

[8 rows x 41 columns]

In [45]:
df.var()

mob_inet                   9.164777e-02
fix_inet                   8.718477e-02
fix_ctv                    8.568336e-02
fix_ictv                   7.029135e-02
voice_mob                  2.326531e-01
voice_fix                  1.840823e-01
sms                        9.750223e-02
csd                        9.312169e-02
iot                        6.072631e-02
mms                        2.530063e-02
roaming                    1.840823e-01
mg                         9.604892e-02
mn                         7.342472e-02
mts                        6.713049e-02
conc                       7.653061e-02
fix_op                     6.713049e-02
vsr_roam                   1.088813e-01
national_roam              4.085412e-02
mn_roam                    7.186147e-02
voice_ap                   6.233766e-02
voice_fee                  5.091390e-02
period_service             2.503779e-01
one_time_service           2.486463e-01
dop_service                1.452450e-01
content                    1.100804e-02


In [46]:
df.rename(columns={'equipment rent':'equipment_rent'}, inplace=True)

In [47]:
#разбиваем датасет на тренировочную и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1] , test_size=0.33, random_state=42)

In [48]:
#Создаем классификатор
clf = DecisionTreeClassifier()

In [49]:
#Обучаем классификатор
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [50]:
#смотрим скор на тренировочной выборке
clf.score(X_train,y_train)

0.9806094182825484

In [51]:
#смотрим скор на тестовой выборке
clf.score(X_test,y_test)

0.7877094972067039

In [52]:
#делаем предсказания на тестовой выборке
predictions = clf.predict(X_test)

In [53]:
from sklearn.metrics import classification_report

In [54]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         4
           4       0.33      0.17      0.22         6
           5       0.67      0.50      0.57         4
           6       1.00      0.25      0.40         4
           7       0.67      1.00      0.80         2
           8       0.75      1.00      0.86         3
           9       0.67      1.00      0.80         4
          10       0.50      0.12      0.20         8
          11       1.00      0.25      0.40         4
          12       1.00      0.33      0.50         3
          15       0.50      0.50      0.50         2
          16       1.00      1.00      1.00         2
          22       0.20      0.50      0.29         2
          29       1.00      1.00      1.00         3
          33       1.00      1.00      1.00         2
          90       1.00      1.00      1.00         5
          91       1.00      1.00      1.00         1
          99       0.00    

/home/maksim/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/maksim/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/maksim/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/maksim/minic

In [55]:
#смотрим конфьюжн матрицу 
cf_matrix = confusion_matrix(y_test,predictions)
print(cf_matrix)

[[0 0 1 ... 0 0 0]
 [3 1 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 4 0]
 [0 0 0 ... 0 0 5]]


In [56]:
#смотрим многокласосвую конфьюжн матрицу
multilabel_confusion_matrix(y_test,predictions)

array([[[172,   3],
        [  4,   0]],

       [[171,   2],
        [  5,   1]],

       [[174,   1],
        [  2,   2]],

       [[175,   0],
        [  3,   1]],

       [[176,   1],
        [  0,   2]],

       [[175,   1],
        [  0,   3]],

       [[173,   2],
        [  0,   4]],

       [[170,   1],
        [  7,   1]],

       [[175,   0],
        [  3,   1]],

       [[176,   0],
        [  2,   1]],

       [[176,   1],
        [  1,   1]],

       [[177,   0],
        [  0,   2]],

       [[173,   4],
        [  1,   1]],

       [[176,   0],
        [  0,   3]],

       [[177,   0],
        [  0,   2]],

       [[174,   0],
        [  0,   5]],

       [[178,   0],
        [  0,   1]],

       [[178,   1],
        [  0,   0]],

       [[175,   0],
        [  1,   3]],

       [[175,   0],
        [  0,   4]],

       [[175,   1],
        [  0,   3]],

       [[174,   2],
        [  0,   3]],

       [[173,   3],
        [  1,   2]],

       [[176,   1],
        [  0, 

In [57]:
#Делаем новое предсказание на совсем новых данных
    #  mob_inet,fix_inet,fix_ctv,fix_ictv,voice_mob,voice_fix,sms,csd,iot,mms,roaming,mg,mn,mts,conc,fix_op,vsr_roam,national_roam,mn_roam,voice_ap,voice_fee,period_service,one_time_service,dop_service,content,services_service,keo_sale,discount,only_inbound,sms_a2p,sms_gross,skoring,other_service,voice_mail,geo,ep_for_number,ep_for_line,one-time_fee_for_number,equipment rent,add_package
X_new=[[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0,0,0,0,0,0,0,0,0]]

In [58]:
clf.predict(X_new)
#предсказан пятый класс

/home/maksim/miniconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([103])

In [59]:
#можем посмотреть в датасете как выглядит 1006-й класс
df.loc[df['group_id']==1125]

mob_inet  fix_inet  fix_ctv  fix_ictv  voice_mob  voice_fix  sms  csd  \
350         1         0        0         0          0          0    0    0   
351         1         0        0         0          0          0    0    0   
352         1         0        0         0          0          0    0    0   
353         1         0        0         0          0          0    0    0   
354         1         0        0         0          0          0    0    0   
355         1         0        0         0          0          0    0    0   
356         1         0        0         0          0          0    0    0   
357         1         0        0         0          0          0    0    0   
358         1         0        0         0          0          0    0    0   
359         1         0        0         0          0          0    0    0   

     iot  mms  ...  skoring  other_service  voice_mail  geo  ep_for_number  \
350    1    0  ...        0              0           0    0              0   
351    1    0  ...        0              0           0    0              0   
352    1    0  ...        0              0           0    0              0   
353    1    0  ...        0              0           0    0              0   
354    1    0  ...        0              0           0    0              0   
355    1    0  ...        0              0           0    0              0   
356    1    0  ...        0              0           0    0              0   
357    1    0  ...        0              0           0    0              0   
358    1    0  ...        0              0           0    0              0   
359    1    0  ...        0              0           0    0              0   

     ep_for_line  one-time_fee_for_number  equipment_rent  add_package  \
350            0                        0               0            0   
351            0                        0               0            0   
352            0                        0               0            0   
353            0                        0               0            0   
354            0                        0               0            0   
355            0                        0               0            0   
356            0                        0               0            0   
357            0                        0               0            0   
358            0                        0               0            0   
359            0                        0               0            0   

     group_id  
350      1125  
351      1125  
352      1125  
353      1125  
354      1125  
355      1125  
356      1125  
357      1125  
358      1125  
359      1125  

[10 rows x 41 columns]

# Training the Random Forest model

In [60]:
from sklearn.ensemble import RandomForestClassifier

In [61]:
rfc = RandomForestClassifier(n_estimators=600)

In [62]:
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=600)

In [63]:
#смотрим скор на тренировочной выборке
rfc.score(X_train,y_train)

0.9806094182825484

In [64]:
#смотрим скор на тестовой выборке
rfc.score(X_test,y_test)

0.8324022346368715

In [65]:
predictions = rfc.predict(X_test)

In [66]:
from sklearn.metrics import classification_report,confusion_matrix

In [67]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.33      0.25      0.29         4
           4       0.67      0.33      0.44         6
           5       0.75      0.75      0.75         4
           6       1.00      0.75      0.86         4
           7       0.67      1.00      0.80         2
           8       1.00      1.00      1.00         3
           9       1.00      0.75      0.86         4
          10       1.00      0.12      0.22         8
          11       0.60      0.75      0.67         4
          12       0.67      0.67      0.67         3
          15       0.67      1.00      0.80         2
          16       1.00      1.00      1.00         2
          22       0.33      0.50      0.40         2
          29       0.75      1.00      0.86         3
          33       1.00      1.00      1.00         2
          90       1.00      1.00      1.00         5
          91       1.00      1.00      1.00         1
         100       1.00    

In [68]:
print(confusion_matrix(y_test,predictions))

[[1 0 1 ... 0 0 0]
 [2 2 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 4 0]
 [0 0 0 ... 0 0 5]]


In [69]:
plt.figure(figsize=(10,6))
df[df['mob_inet']==1]['mob_inet'].hist(alpha=1,color='blue',
                                              bins=5,label='mob_inet=1')
df[df['mob_inet']==0]['mob_inet'].hist(alpha=1,color='red',
                                              bins=5,label='mob_inet=0')
plt.legend()
plt.xlabel('group_id')

Text(0.5, 0, 'group_id')

In [70]:
#Делаем новое предсказание на совсем новых данных
    #  mob_inet,fix_inet,fix_ctv,fix_ictv,voice_mob,voice_fix,sms,csd,iot,mms,roaming,mg,mn,mts,conc,fix_op,vsr_roam,national_roam,mn_roam,voice_ap,voice_fee,period_service,one_time_service,dop_service,content,services_service,keo_sale,discount,only_inbound,sms_a2p,sms_gross,skoring,other_service,voice_mail,geo,ep_for_number,ep_for_line,one-time_fee_for_number,equipment rent,add_package
X_new=[[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0,0,0,0,0,1,0,0,0]]

In [71]:
rfc.predict(X_new)
#предсказан 1006 класс

/home/maksim/miniconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([3002])

In [72]:
sns.jointplot(x='mob_inet',y='group_id',data=df,color='purple')
sns.jointplot(x='fix_inet',y='group_id',data=df,color='purple')
sns.jointplot(x='voice_mob',y='group_id',data=df,color='purple')
sns.jointplot(x='fix_ctv',y='group_id',data=df,color='purple')
sns.jointplot(x='fix_ictv',y='group_id',data=df,color='purple')
sns.jointplot(x='voice_fix',y='group_id',data=df,color='purple')



#sms,csd,iot,mms,roaming,mg,mn,mts,conc,fix_op,vsr_roam,national_roam,mn_roam,voice_ap,voice_fee,period_service,one_time_service,dop_service,content,services_service,keo_sale,discount,only_inbound,sms_a2p,sms_gross,skoring,other_service,voice_mail,geo,ep_for_number,ep_for_line,one-time_fee_for_number,equipment rent,add_package

In [78]:
import joblib
joblib.dump(rfc, 'model.pkl')

['model.pkl']

# Training the XGboost model

In [73]:
from xgboost import XGBClassifier

In [74]:
#pip install xgboost

In [75]:
#conda install py-xgboost

In [76]:
import xgboost as xgb

xgb_cl = xgb.XGBClassifier()

In [77]:
#Обучаем классификатор
xgb_cl.fit(X_train,y_train)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54], got [   1    4    5    6    7    8    9   10   11   12   15   16   22   29
   33   90   91   99  100  101  102  103  104  105 1001 1004 1006 1007
 1016 1027 1030 1033 1034 1100 1121 1124 1125 1126 3001 3002 3003 3009
 3010 3019 3020 3031 3309 3311 3312 3313 3314 3320 3321 3322 3323]

In [21]:
#смотрим скор на тренировочной выборке
xgb_cl.score(X_train,y_train)

0.9722991689750693

In [22]:
#смотрим скор на тестовой выборке
xgb_cl.score(X_test,y_test)

0.8044692737430168

In [23]:
#делаем предсказания на тестовой выборке
predictions = xgb_cl.predict(X_test)

In [24]:
#смотрим конфьюжн матрицу 
confusion_matrix(y_test,predictions)

array([[3, 0, 1, ..., 0, 0, 0],
       [2, 2, 0, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 3, 0, 0],
       [0, 0, 0, ..., 0, 4, 0],
       [0, 0, 0, ..., 0, 0, 5]])

In [25]:
#смотрим многокласосвую конфьюжн матрицу
multilabel_confusion_matrix(y_test,predictions)

array([[[171,   4],
        [  1,   3]],

       [[171,   2],
        [  4,   2]],

       [[174,   1],
        [  2,   2]],

       [[173,   2],
        [  1,   3]],

       [[176,   1],
        [  0,   2]],

       [[175,   1],
        [  0,   3]],

       [[175,   0],
        [  1,   3]],

       [[171,   0],
        [  7,   1]],

       [[174,   1],
        [  1,   3]],

       [[176,   0],
        [  1,   2]],

       [[176,   1],
        [  0,   2]],

       [[177,   0],
        [  0,   2]],

       [[174,   3],
        [  1,   1]],

       [[175,   1],
        [  1,   2]],

       [[177,   0],
        [  0,   2]],

       [[174,   0],
        [  0,   5]],

       [[178,   0],
        [  0,   1]],

       [[175,   0],
        [  0,   4]],

       [[175,   0],
        [  0,   4]],

       [[176,   0],
        [  0,   3]],

       [[176,   0],
        [  1,   2]],

       [[174,   2],
        [  1,   2]],

       [[176,   1],
        [  0,   2]],

       [[175,   1],
        [  2, 

In [29]:
from sklearn.metrics import classification_report

In [30]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.43      0.75      0.55         4
           4       0.50      0.33      0.40         6
           5       0.67      0.50      0.57         4
           6       0.60      0.75      0.67         4
           7       0.67      1.00      0.80         2
           8       0.75      1.00      0.86         3
           9       1.00      0.75      0.86         4
          10       1.00      0.12      0.22         8
          11       0.75      0.75      0.75         4
          12       1.00      0.67      0.80         3
          15       0.67      1.00      0.80         2
          16       1.00      1.00      1.00         2
          22       0.25      0.50      0.33         2
          29       0.67      0.67      0.67         3
          33       1.00      1.00      1.00         2
          90       1.00      1.00      1.00         5
          91       1.00      1.00      1.00         1
         100       1.00    